import Paths from '#utils/paths'
import type { MergedLine } from './types'

const FINAL_SENTENTH_DURATION_IN_SEC = 5

function buildASS(lines: MergedLine[]) {
    const assLines: {
        text: string
        startTime: number
        endTime?: number
        style: string
    }[] = []
    lines.forEach((line) => {
        let text: string | undefined
        let style = 'Default'
        let startTime = 0
        let prefix = ''

        switch (line._t) {
            case 'MWV':
                style = line.actorId || 'Default'
                prefix = line.name ? `${line.name}: ` : ''
                startTime = line.startTime
                text = line.text
                break
            case 'Message':
                startTime = line.startTime
                text = line.text
                break
            case 'Narration':
                startTime = line.startTime
                text = `(${line.text})`
                break
        }

        if (text === undefined) {
            return
        }

        const lineText = (prefix + text)
            .replaceAll('\\n', '\\N')
            .replaceAll('{user}', '[マネジャー]')
        assLines.push({
            startTime,
            text: lineText,
            style,
        })
        if (assLines.length > 1) {
            assLines[assLines.length - 2].endTime = startTime
        }
    })

    return assLines
}

export function generateASS(lines: MergedLine[], title: string): string {
    const actorStyles = new Set<string>()
    lines.forEach((line) => {
        if (line._t === 'MWV' && line.actorId) {
            actorStyles.add(line.actorId)
        }
    })

    let styles = `Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,8,2,0,5,20,20,23,1\n`
    actorStyles.forEach((actorId) => {
        styles += `Style: ${actorId},Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,8,2,0,5,20,20,23,1\n`
    })

    const assBase = `[Script Info]
; Generated by info-pride
; ${Paths.self('')}
Title: ${title}
ScriptType: v4.00+

[V4+ Styles]
${styles}
[Events]`

    const assLines = buildASS(lines)

    return [
        assBase,
        ...assLines.map(
            ({ startTime, endTime, style, text }) =>
                `Dialogue: 0,${formatTime(startTime)},${formatTime(endTime ?? startTime + FINAL_SENTENTH_DURATION_IN_SEC)},${style},,0,0,0,,${text}`,
        ),
    ].join('\n')
}

export function generateText(lines: MergedLine[], title: string): string {
    const assLines = buildASS(lines)

    return title + '\n\n' + assLines.map((x) => x.text).join('\n')
}

function formatTime(sec: number): string {
    const ms = sec * 1000
    const totalSeconds = Math.floor(ms / 1000)
    const hours = Math.floor(totalSeconds / 3600)
    const minutes = Math.floor((totalSeconds % 3600) / 60)
    const seconds = totalSeconds % 60
    const centiseconds = Math.floor((ms % 1000) / 10)
    return `${hours}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}.${centiseconds.toString().padStart(2, '0')}`
}
