/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Translated diary text, in HTML
 */
export type DiaryText = string
/**
 * Diary in-game date in YY-MM-DD
 */
export type DiaryDate = string
/**
 * The container of the data.
 */
export type TheTable = DiaryItem[]

/**
 * Diary data for wiki.biligame.com/idolypride
 */
export interface TheRootSchema {
    tb: TheTable
    additionalProperties?: false
    [k: string]: unknown
}
/**
 * An diary item
 */
export interface DiaryItem {
    diary: DiaryText
    date: DiaryDate
}
