/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Card data for wiki.biligame.com/idolypride
 */
export interface TheRootSchema {
  长濑麻奈: CardsFromAnIdol;
  川咲樱: CardsFromAnIdol;
  一之濑怜: CardsFromAnIdol;
  佐伯遥子: CardsFromAnIdol;
  白石千纱: CardsFromAnIdol;
  兵藤雫: CardsFromAnIdol;
  长濑琴乃: CardsFromAnIdol;
  伊吹渚: CardsFromAnIdol;
  白石沙季: CardsFromAnIdol;
  成宫铃: CardsFromAnIdol;
  早坂芽衣: CardsFromAnIdol;
  天动瑠依: CardsFromAnIdol;
  铃村优: CardsFromAnIdol;
  奥山堇: CardsFromAnIdol;
  神崎莉央: CardsFromAnIdol;
  井川葵: CardsFromAnIdol;
  小美山爱: CardsFromAnIdol;
  赤崎心: CardsFromAnIdol;
}
export interface CardsFromAnIdol {
  [k: string]: Card;
}
export interface Card {
  ownerName:
    | "长濑麻奈"
    | "川咲樱"
    | "一之濑怜"
    | "佐伯遥子"
    | "白石千纱"
    | "兵藤雫"
    | "长濑琴乃"
    | "伊吹渚"
    | "白石沙季"
    | "成宫铃"
    | "早坂芽衣"
    | "天动瑠依"
    | "铃村优"
    | "奥山堇"
    | "神崎莉央"
    | "井川葵"
    | "小美山爱"
    | "赤崎心";
  ownerId: number;
  type: "支援" | "辅助" | "得分";
  rarity: number;
  prop: "舞蹈" | "歌唱" | "表演";
  ski1Typ: "SP" | "A";
  ski2Typ: "A" | "P";
  ski3Typ: "A" | "P";
  vocTop: number;
  danTop: number;
  visTop: number;
  staTop: number;
  nameJa: string;
  nameCn: string;
  ski1NameJa: string;
  ski1DescJa: string;
  ski1NameCn: string;
  ski1DescCn: string;
  ski2NameJa: string;
  ski2DescJa: string;
  ski2NameCn: string;
  ski2DescCn: string;
  ski3NameJa: string;
  ski3DescJa: string;
  ski3NameCn: string;
  ski3DescCn: string;
  eruNameJa?: string;
  eruDescJa?: string;
  eruNameCn?: string;
  eruDescCn?: string;
  [k: string]: unknown;
}
