/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NameInJapanese = string;
export type NameInChinese = string;
export type Description = string;

/**
 * Idol data for wiki.biligame.com/idolypride
 */
export interface TheRootSchema {
  长濑麻奈: IdolInfo;
  川咲樱: IdolInfo;
  一之濑怜: IdolInfo;
  佐伯遥子: IdolInfo;
  白石千纱: IdolInfo;
  兵藤雫: IdolInfo;
  长濑琴乃: IdolInfo;
  伊吹渚: IdolInfo;
  白石沙季: IdolInfo;
  成宫铃: IdolInfo;
  早坂芽衣: IdolInfo;
  天动瑠依: IdolInfo;
  铃村优: IdolInfo;
  奥山堇: IdolInfo;
  神崎莉央: IdolInfo;
  井川葵: IdolInfo;
  小美山爱: IdolInfo;
  赤崎心: IdolInfo;
}
/**
 * Information for an idol
 */
export interface IdolInfo {
  nameJa?: NameInJapanese;
  nameCn?: NameInChinese;
  birthday?: string;
  team?: "月のテンペスト" | "サニーピース" | "星见事务所" | "TRINITYAiLE" | "LizNoir";
  cv?: string;
  desc?: Description;
  [k: string]: unknown;
}
