name: Update dataset

on:
    schedule:
        # Update Thu 04:15 (CST) per week
        - cron: '15 20 * * 3'
    workflow_dispatch: {}

jobs:
    update_dataset:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: |
                  sudo apt install -y lua5.4
                  sudo npm install -g pnpm
                  pnpm install esbuild-register

            - name: Build & Validate
              run: |
                  bash scripts/buildAndValidate.sh
                  node scripts/updateVendorStrings.mjs
                  node scripts/updateStoryList.mjs

            - name: Commit files
              id: commit
              continue-on-error: true
              run: |
                  git config --local user.email "noreply@outv.im"
                  git config --local user.name "GitHub Actions"
                  git add data/ locales/
                  git status
                  if git commit -m "feat: update dataset"; then
                      echo "has_changes=true" >> "$GITHUB_OUTPUT"
                      git pull --rebase
                  else
                      echo "has_changes=false" >> "$GITHUB_OUTPUT"
                  fi

            - name: Push changes
              if: steps.commit.outputs.has_changes == 'true'
              uses: ad-m/github-push-action@master
              with:
                  branch: master
                  github_token: ${{ secrets.GITHUB_TOKEN }}
