name: Validate locale

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  check_locale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt install -y lua5.3
          sudo npm install -g pnpm
          pnpm install

      - name: Build & Validate
        run: node scripts/check-locale.mjs
